### PR TITLE
Fix test_network_cut_affecting_an_instance

### LINKED ISSUE #157: `test_network_cut_affecting_an_instance` broken
In the last 6 days, self-healing integration test `test_network_cut_affecting_an_instance` failed 4 times ([1](https://github.com/canonical/mysql-k8s-operator/actions/runs/4208902052/jobs/7305613327), [2](https://github.com/canonical/mysql-k8s-operator/actions/runs/4213899312/jobs/7314001381), [3](https://github.com/canonical/mysql-k8s-operator/actions/runs/4228341630/jobs/7344527216), [4](https://github.com/canonical/mysql-k8s-operator/actions/runs/4238423426/jobs/7365689382))

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**
## Issue
Test broken by #131
Fixes #157

### CODE REVIEW

File: tests/integration/high_availability/scripts/deploy_chaos_mesh.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ if [ -z "${chaos_mesh_ns}" ]; then
 fi
 
 deploy_chaos_mesh() {
-	if sg microk8s -c 'microk8s.helm3 repo list' | grep -q 'chaos-mesh'; then
```
Comment (paulomach) [inline tests/integration/high_availability/scripts/deploy_chaos_mesh.sh:14]: I think adding the repo should be called without the test, because it does not error out when the repo is already added.

**Review by paulomach — APPROVED** [review]

**Review by taurus-forever — APPROVED** [review]

**Comment by taurus-forever** [comment]
Nice catch Carl! Apologies for the regression.
For some reason self-healing test was [not executed](https://github.com/canonical/mysql-k8s-operator/actions/runs/4044435561/jobs/6955639852) in [PR#131](https://github.com/canonical/mysql-k8s-operator/pull/131) (not yet committed/enabled)?

**Comment by taurus-forever** [comment]
> It was disabled in #133

It explains why tests passed in [PR#131](https://github.com/canonical/mysql-k8s-operator/pull/131). Tnx!
